# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/ikamensh/flynt
    rev: "1.0.1"
    hooks:
      - id: flynt
        args: [--line-length, "120"]

  - repo: https://github.com/PyCQA/autoflake # configuration in pyproject.toml
    rev: "v2.2.1"
    hooks:
      - id: autoflake
        args: []

  # isort and black should be after other python hooks
  - repo: https://github.com/pycqa/isort # configuration in pyproject.toml
    rev: "5.12.0"
    hooks:
      - id: isort
        name: isort (python)

  # isort and black should be after other python hooks, black should be after isort
  - repo: https://github.com/psf/black # configuration in pyproject.toml
    rev: "23.7.0" # If you updated this, also update in pyproject.toml
    hooks:
      - id: black

  # this should be the last hook
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: |
          (?x)^(
            \.vscode/.*\.json
          )$
      - id: check-added-large-files
      - id: fix-encoding-pragma
        args: [--remove]
      - id: check-merge-conflict
