# Generated by Django 4.2.5 on 2023-09-08 09:55

import django.core.validators
from django.db import migrations, models

# def update_resolved(app, _):
#     Contact = app.get_model("contact", "Contact")
#     Contact.objects.filter(resolved=True).update(state="resolved")


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_csat"),
    ]

    operations = [
        # This was an example of how to add a new field to a model and populate it with data:
        # migrations.AddField(
        #     model_name="contact",
        #     name="state",
        #     field=models.CharField(
        #         choices=[("resolved", "Resolved"), ("pending", "Pending")], default="pending", max_length=20
        #     ),
        # ),
        # migrations.RunPython(code=update_resolved, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        "^09[0-9]+$", "Phone number should be 11 digits and start with 09."
                    ),
                    django.core.validators.MinLengthValidator(11),
                ],
            ),
        ),
    ]
